# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/limke/Desktop/2026 project/FDP/FDP_2026.srcs/sources_1/ip/cordic_ip_core/cordic_ip_core.xci
# IP: The module: 'cordic_ip_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/limke/Desktop/2026 project/FDP/FDP_2026.srcs/sources_1/ip/cordic_ip_core/cordic_ip_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_ip_core'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/limke/Desktop/2026 project/FDP/FDP_2026.srcs/sources_1/ip/cordic_ip_core/cordic_ip_core.xci
# IP: The module: 'cordic_ip_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/limke/Desktop/2026 project/FDP/FDP_2026.srcs/sources_1/ip/cordic_ip_core/cordic_ip_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_ip_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
